### ISSUE TITLE
Create continious integration for repository 

### ISSUE THREAD

**Issue by henrym2** [GoogleChromeLabs/IseWebSecurityBundle#2]
## Expected Behavior
Travis CI continious integration testing, such that each PR has the test suite run against it through travis

## Actual Behavior
No CI service implemented

## Steps to build a solution
1. Setup Travis CI integration
2. Create workflow
3. Test workflow
4. Apply workflow to repository.

**Comment by rowan-m** [comment]
You can take a look at what I've done in https://github.com/google/recaptcha for:

- Travis configuration: https://github.com/google/recaptcha/blob/master/.travis.yml
- PHPUnit configuration: https://github.com/google/recaptcha/blob/master/phpunit.xml.dist
- Enforcing code coverage: https://coveralls.io/github/google/recaptcha
- Enforcing coding standards: https://github.com/google/recaptcha/blob/master/composer.json#L31-L32
